### ISSUE TITLE
Ue5.1 updated support?

### ISSUE THREAD

**Issue by oscarbg** [philipturner/ue5-nanite-macos#2]

**Comment by philipturner** [comment]
I've basically stopped working on this project, but I'm hoping someone else will continue where I left off. Similar to how the original port by @gladhu was incomplete. The new programmable rasterizer was finished, so my code samples could be a bit outdated. The core concept of an atomics workaround stays the same.

**Comment by philipturner** [comment]
Check the UE5 forum thread. Epic is finally starting to implement Nanite for Mac with UE5.2.
